### ISSUE TITLE
Execute systemd daemon reload every time an init.d service is provisioned

### ISSUE THREAD

**Issue by igobranco** [arquivo/pwa-technologies#503]
`systemctl daemon-reload`

**Comment by igobranco** [comment]
It's resolved using a snippet like:
```yaml
- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes
  when: ansible_service_mgr == 'systemd' and mongos_systemd_unit is changed
```
It could be used on handlers role or directly on tasks.
