### ISSUE TITLE
PDF document identified as DOC 

### ISSUE THREAD

**Issue by arquivo** [arquivo/pwa-technologies#56]
Originally reported on Google Code with ID 57
```
On the result page, "Ficha de Boa Prtica Ambiental" (http://www.arquivo.pt/search.jsp?l=pt&query=type%3Adoc+boa+prática)
is identified as DOC but is a PDF document.

This misinformation seems to be caused by the message provided by the original server:

  HTTP/1.1 200 OK
  Date: Fri, 30 Nov 2012 11:02:23 GMT
  Server: Microsoft-IIS/6.0
  header: 
  X-AspNet-Version: 1.1.4322
  Content-Disposition: attachment; filename=manualboaspraticas.pdf
  Connection: close
  X-Powered-By: ASP.NET
  Cache-Control: private, max-age=315360000
  Content-Type: application/doc
  Content-Length: 5781208
  Expires: Mon, 28 Nov 2022 11:02:23 GMT
```

Reported by `whispsil` on 2012-11-30 15:49:30
